### ISSUE TITLE
Markdown記法のリストブロックの終了について

### ISSUE THREAD

**Issue by 1484** [nabe-abk/adiary#10]
Markdown記法でリストを記載、リストブロックを終わらせ次のブロックの文章を書くため空行を挟んでもブロックの終了とならないようです。
リストブロックの後に空行があり、その次の行がリストブロックではない場合には `</ul>` でリストを終了して欲しい。

拙い説明で分かりづらいと思いましたので[お試しブログで記法を試しました](https://test.adiary.jp/02972)。

**Comment by nabe-abk** [comment]
ご指摘ありがとうございます。Ver3.50eにて修正しました。
