### ISSUE TITLE
adiary公式ページのadiaryユーザ会のリンク先が文字化けします

### ISSUE THREAD

**Issue by honda0510** [nabe-abk/adiary#3]
http://adiary.jp/
![2015-01-18 10 22 54](https://cloud.githubusercontent.com/assets/568510/5791068/11ac99ae-9efc-11e4-96e4-06259ecdbe18.png)

**Comment by nabe-abk** [comment]
文字化けは承知してますが、
adiary.jpのサーバは管轄外なのです--;;;;
