### ISSUE TITLE
下書き保存した記事の日付

### ISSUE THREAD

**Issue by Sabazo** [nabe-abk/adiary#4]
下書き保存した記事を、別の日に編集しようと開くと日付欄がその日(編集日)になりますが、これは仕様でしょうか?
できれば下書き保存した日付にして欲しいです。

**Comment by nabe-abk** [comment]
仕様になります。記事日付は「その記事を作成した日（完成させて公開した日）」という理解です。
日付の保存が必要でしたら、非公開設定で保存してください。

**Comment by Sabazo** [comment]
了解しました。
本文に日付を書いて下書き保存するような使い方にします。
日記はその日のうちに書けよって話ですよね(^^;
ありがとうございました。
