### ISSUE TITLE
Markdown使用時の軽微なバグ

### ISSUE THREAD

**Issue by pawa-** [nabe-abk/adiary#5]
記事内に
`[ほげ](http://example.com/_hoge_)`
と書くと、
`<a href="http://example.com/_hoge_">ほげ</a>`
でなく
 `<a href="http://example.com/&lt;em&gt;hoge&lt;/em&gt;">ほげ</a>`
となってしまいます。

よろしくお願いします。

**Comment by nabe-abk** [comment]
ご指摘ありがとうございます。
Ver3.14にて修正しました。
リリースまで少々おまちください。

**Comment by pawa-** [comment]
ありがとうございます。修正確認できました！
