### ISSUE TITLE
新規記事を投稿する際に本文入力のtextboxに不要な文字列が出る

### ISSUE THREAD

**Issue by 1484** [nabe-abk/adiary#6]
右上の `書く` リンクから新規投稿しようとすると入力フォームの本文部分のtextboxに次の文字が出ます。

```
 <figure class="
		そのまま
		センタリング
		左寄せ（回り込み）
		右寄せ（回り込み）
	"></figure>
```

**Comment by nabe-abk** [comment]
全く再現しないのですが、以下お知らせください。

・使用している adiary の Version
・使用しているブラウザとそのVersion
・設定している入力記法

その他設置環境として特殊な条件がある場合はお知らせください。

**Comment by 1484** [comment]
すみません、環境書くの忘れてました。
いくつかの環境で試したのですが、発生するのは次の環境のみです。

- adiary version
-- 3.24
- 利用ブラウザ
-- chrome 74.0.3729.157
- 利用OS
-- android9
- 入力記法
-- Markdown

iPadProのSafariなどでは問題なく、android端末のchromeでのみ発生しています。
ブラウザの設定でPCサイトとして開いても同様に出ます。

reverse proxyなど特殊な設定はしていません。
FastCGIなども用いていません。

**Comment by nabe-abk** [comment]
Android 9は残念ながら端末がないので、
Android 8.1 で同じVersionのChromeを試しましたが、問題は再現しませんでした……。

大変お手数ですが、テストサイトでも同じ現象が起こるか確認して頂けますか？
[https://test.adiary.jp/](https://test.adiary.jp/)

**Comment by 1484** [comment]
testサイトで確認しましたが特に問題なかったのでdiffで追い込んでいきました。
その結果、js配下にあるファイルに差分があったので下記2ファイルを消した所現象が解消しました。

`adiary` がgitで持ってきたもの、 `diary` が問題のサイトから持ってきたもの
> $ diff -rq adiary/ diary/ | more
((中略))
diary/js のみに存在: jquery-3.min.js
diary/js のみに存在: jquery-3.min.map

環境問題である事が判明しました、大変お騒がせしました。

**Comment by nabe-abk** [comment]
ご確認ありがとうございます。原因は、JavaScriptファイルの更新検出用の仕組みが完全でなかったため、環境によって（Android版Chrome等で）edit.jsの更新読込に失敗していたようです。

js/以下のファイルを消すと問題が解消するのは、jsディレクトリの更新日時が新しくなりjs/edit.jsが正しくリロードされたためと思われます。

この問題は次期バージョンで修正予定です。ご報告ありがとうございました。
