### ISSUE TITLE
varをletとconstに

### ISSUE THREAD

**Issue by KisaragiEffective** [nabe-abk/adiary#7]
`var`で宣言されたローカル変数を`let`と`const`に切り分けるとパフォーマンス向上が見込まれる。
なお、`let`と`const`は[MDN - let](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/let)と[MDN - const](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/const)でIE11、edge、FireFoxに対応していることが表記されているため、現在の必要環境を上げる必要はない。

**Comment by nabe-abk** [comment]
JavaScriptを新しく書いた分（整理した分）については const/let していますが、全部を書き直すのは躊躇しています。

- var を let/const に書き換えることでエンバグする可能性が非常に高い。
- 労力に対してパフォーマンス効果は微々たるもの。
- IE11は、for文内でconstを使うと問題が起きる。

次バージョンでJSまわりは大幅に手が入っていますので、その後、手の空いている方が**慎重に**変更していただければ幸いです。
